mariadb:
  architecture: "standalone"
  auth:
    database: "golist"
    username: "golist"
    password: "golist"
  image:
    registry: docker.io
    repository: bitnami/mariadb
    tag: latest
    digest: ""     # IMPORTANT: must stay empty if tag is used
    pullPolicy: IfNotPresent
